produtos:
- nome: Leite
  preco: 3.49
  quantidade: 20
- nome: "P\xC3\xA3o"
  preco: 2.29
  quantidade: 35
- nome: Ovos
  preco: 5.99
  quantidade: 12
- nome: "Ma\xC3\xA7\xC3\xA3s"
  preco: 4.25
  quantidade: 50
- nome: "Papel Higi\xC3\xAAnico"
  quantidade: 15
- preco: 5.0
  produto: acerola
  quantidade: 600
- preco: 5.0
  produto: acerola
  quantidade: 600
